### ISSUE TITLE
Problem with adapter

### ISSUE THREAD

**Issue by laylizzlle** [mutualmobile/CardStackUI#11]
I want to create a card stack ui with a varying number and am getting a NullExceptionPointer because the getCount method is called before the constructor. This is my code:

    public class QuestionStackAdapter extends CardStackAdapter {

    private final LayoutInflater mInflater;
    private final Context mContext;
    private ArrayList<String> root_words;

    private static int[] bgColorIds = {
            R.color.card1_bg,
            R.color.card2_bg,
            R.color.card3_bg,
            R.color.card4_bg,
            R.color.card5_bg,
            R.color.card6_bg,
            R.color.card7_bg
    };

    public QuestionStackAdapter(Questions activity,ArrayList<String> root_words) {
        super(activity);
        mContext = activity;
        mInflater = LayoutInflater.from(activity);
        this.root_words = root_words;
    }

    @Override
    public View createView(int position, ViewGroup container) {
        CardView root = (CardView) mInflater.inflate(R.layout.questions_card, container, false);
        root.setCardBackgroundColor(ContextCompat.getColor(mContext, bgColorIds[position]));
        TextView cardTitle = (TextView) root.findViewById(R.id.card_title);
        cardTitle.setText(root_words.get(position));
        return root;
    }

    @Override
    public int getCount() {
       // error occurs here but works when i use length of bgColorIds which isn't going
       // to help me because the number of cards i need to generate will vary every time
        return root_words.size();
    }
}

**Comment by tushar-acharya** [comment]
Please use the 0.3 version to fix the above issue. And thanks for bringing it to our notice!

**Comment by laylizzlle** [comment]
You welcome but am getting failed to resolve: com.mutualmobile.android:cardstack:0.3

**Comment by tushar-acharya** [comment]
Fixed it. Please use version 0.4.4
