### ISSUE TITLE
Scroll Upward not working

### ISSUE THREAD

**Issue by BilalRabbani** [mutualmobile/CardStackUI#14]
Thanks for the wonderful library but here I need some help. I placed 15 cards in the stack but now it doesn't scroll upward and it only show top 8 cards. How do I make it scroll upward ? Secondly if I have lesser cards, for instance 4, then I want to scroll upward direction to view last card fully.

**Comment by tushar-acharya** [comment]
@BilalRabbani You're actually asking for something like Lollipop recent apps view. This library was built for a different use case. You can checkout this other library if it suits your use case - https://github.com/ZieIony/MaterialRecents
