### ISSUE TITLE
ScrollView 

### ISSUE THREAD

**Issue by pirokinez78** [mutualmobile/CardStackUI#17]
CardsLayout does not work with ScrollView

**Comment by OmkarAmberkar** [comment]
+1

**Comment by DoM4** [comment]
Has anyone found a solution for this issue? I can't get the stack working with a NestedScrollView.

**Comment by OmkarAmberkar** [comment]
Is there any work around for this?

**Comment by tushar-acharya** [comment]
I'm working on a potential fix for this issue. Should get something out in a couple of days.

**Comment by tushar-acharya** [comment]
Released version 0.5.0 with scroll support
