### ISSUE TITLE
Cards open on touch down, change to touch up please

### ISSUE THREAD

**Issue by TimboMachimbo** [mutualmobile/CardStackUI#19]
This layout is absolutely amazing visually.

However, I am using it inside of a viewpager, and it does not behave well with swiping, because it opens cards based on a touch down event, whereas I feel a more natural approach would be to respond to touch up events for selecting cards.

Thank you.

**Comment by tushar-acharya** [comment]
Card selection currently happens on Touch Up itself. Please look at https://github.com/mutualmobile/CardStackUI/blob/master/cardstack/src/main/java/com/mutualmobile/cardstack/CardStackAdapter.java#L199

**Comment by tushar-acharya** [comment]
It was due to ACTION_CANCEL happening during scroll. Fixed it
